Add geometry, created_geometry, updated_geometry fields to results for queries
fulcrumapp/fulcrum-query-sql pull request #60
Opened 2023-09-13 16:00 UTC by corporealshift

Without these fields geometry does not get returned from query even when it is available

2023-09-13 17:48 UTC, Jirles submitted a review, later dismissed
💥 💥 🎉 🎉 🥳 🥳 

it works

2023-09-13 18:06 UTC, jacobpayne659 approved these changes

2023-09-13 18:14 UTC, dotconde submitted a review, later dismissed

2023-09-13 18:57 UTC, osbornk reviewed
Need to bump the version in `package.json`.

2023-09-13 18:58 UTC, osbornk requested changes
Need to bump the version in `package.json`.

2023-09-14 15:18 UTC, Jirles approved these changes

2023-09-14 15:20 UTC, osbornk approved these changes

2023-09-14 19:26 UTC, merged